### ISSUE TITLE
No proper support for  `aten::triu` OP inputs when inputs are CallNodes [Bug] 

### ISSUE THREAD

**Issue by JushBJJ** [tenstorrent/tt-tvm#3]
Hi I'm doing the bounties with @marty1885 and @JonathanALevine.

### Context
When attempting to implement Qwen 1.5 (0.5B) https://github.com/tenstorrent/tt-buda-demos/issues/20,  we encountered an issue where we had this error:
```python
Traceback (most recent call last):
  File "/home/jush/qwen/.venv/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 536, in triu
    mask = tri(*m.shape[-2:], k=k-1, dtype=bool)
  File "/home/jush/qwen/.venv/lib/python3.8/site-packages/tvm/relay/expr.py", line 146, in __sub__
    raise TypeError(f'convert "{str(other)}" with `const` first')
TypeError: convert "1" with `const` first
````

Qwen 1.5 (0.5B) implementation demo can be found in https://github.com/tenstorrent/tt-buda-demos/pull/37

The OP code in this case for triu would be:
```python
%aten::triu_0_0 : Int(256, 256, strides=[256, 1], requires_grad=0, device=cpu) = aten::triu(%aten::ones_like_0_0, %aten::Int_7_0), scope: utils.modeling_qwen2.Qwen2ForCausalLM::/utils.modeling_qwen2.Qwen2Model::model # /home/jush/qwen/.venv/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py:169:0
```
*Requires [transformers >=v4.37.0](https://github.com/huggingface/transformers/releases/tag/v4.37.0)

### Root Cause
The `triu` function in the PyTorchOpConverter class in `tvm/relay/frontend/pytorch.py` uses np.triu to handle these inputs.

`mask = np.triu(np.ones(x_shape), inputs[1]).astype(np.bool)`

However, it is not possible to handle these input types when the `inputs` parameter is a list containing nested functions. In this case, `inputs[1]` would be:
```
CallNode(Op(add), [CallNode(Op(subtract), [CallNode(Op(subtract), [CallNode(Op(add), [Constant(256), Constant(0)], (nullptr), []), CallNode(Op(multiply), [Constant(1), Constant(256)], (nullptr), [])], (nullptr), []), CallNode(Op(multiply), [Constant(1), Constant(32768)], (nullptr), [])], (nullptr), []), Constant(1)], (nullptr), [])
```

### Workaround
In draft PR https://github.com/tenstorrent/tt-tvm/pull/2, I used `self.trilu(inputs, input_types, mode="triu")` simply because `_op.trilu` can do triangular upper instead of triangular bottom if `upper=True`.

```python
def trilu(self, inputs, input_types, mode):
    data = inputs[0]
    k = inputs[1] if inputs[1] else 0
    upper = True if mode == "triu" else False
    return _op.trilu(data, k, upper)
```

This workaround successfully compiles the Qwen 1.5 (0.5B) model but was still unable to properly run.

See https://github.com/tenstorrent/tt-tvm/pull/2 to see the issues of this workaround.

### Environment

OS: Ubuntu 20.04
Pybuda Version: [v0.10.5.gs.240315](https://github.com/tenstorrent/tt-buda/releases/tag/v0.10.5.gs.240315)
TVM Version (from latest Pybuda): 0.14.0

### Steps to reproduce

See https://github.com/tenstorrent/tt-buda-demos/pull/37

### Triage

frontend:pytorch

**Comment by staylorTT** [comment]
Hi There, thanks for filing this issue. I will do my best to get someone to take a look at this from the TT side.

**Comment by Lewis300** [comment]
Hi all. I’ve been tinkering with this bounty today and I’ve hit a roadblock that I don’t see mentioned here yet. 

So, when forcing output verification with the environment variable PYBUDA_FORCE_VERIFY_ALL=1, I notice that the final TVM model passes (I.e gives same output as the PyTorch model), verification of the pybuda codegen fails. In fact, it returns a tensor of all nan…

Digging into it some more, it appears that the translation of the mask generation fails during the first attention layer, and some nans are generated there. After that the softmax returns all nans. At some point during mask generation (which happens during runtime using the passed-in attention mask) an inf, and -inf are added together, thus giving nan. I’m unsure yet how this problem arises. So I guess next step would be to look into that.

As a side note, I think it is possible to implement tril in tvm with a dynamic diagonal. You must generate the indices of the input shape in a tensor of equal size, and then copy and transpose it. Then add the diagonal to the transposed indices. Take the <= of the indices and transposed + diagonal to get a Boolean mask of what should remain. Then multiply with the input data.

good luck

**Comment by AleksKnezevic** [comment]
To clarify @JushBJJ are the inputs to the op constant (even if they're call nodes). That is, would we be able to extract them using `_infer_value`?

**Comment by JushBJJ** [comment]
> To clarify @JushBJJ are the inputs to the op constant (even if they're call nodes). That is, would we be able to extract them using `_infer_value`?

I will get into this very soon later today, my e75 just arrived yesterday

**Comment by staylorTT** [comment]
@JushBJJ Do you have any updates here?

**Comment by JushBJJ** [comment]
> @JushBJJ Do you have any updates here?

Hi, incredibly sorry for forgetting about this. Since I don't have much to do atm this is full priority now.
Currently trying to pass some Buda hurdles atm with the more recent updates but so far I haven't reached this issue again...yet

**Comment by staylorTT** [comment]
Appreciate the update. If you hit this again please report back.

**Comment by JushBJJ** [comment]
@staylorTT Can confidently confirm that this is no longer an issue anymore. This can stay closed, thanks!

**Comment by JushBJJ** [comment]
@staylorTT Yup this can stay closed, can confirm that this is no longer an issue
